ViewModels/Pagination.cs
namespace Proyecto_Web.ViewModels
{
    public class Pagination
    {
        public int Page { get; set; }

        public int PageSize { get; set; }

        public int Total { get; set; }

        public int PageCount => (int)decimal.Ceiling(Total / (decimal)PageSize);

        public bool HasPrevious => Page > 1;
        public bool HasNext => Page >= 1 && Page < PageCount;
        public static PaginationInfo GetInfo(int page, int pageSize)
        {
            return (new PaginationInfo (page, pageSize));
        }
    }

    public class PaginationInfo
    {
        public int Skip { get; }
        public int Take { get; }
        public PaginationInfo(int page, int pageSize)
        {
            Skip = (page - 1) * pageSize;
            Take = pageSize;
    
        }
    }
}

Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proyecto_Web.Constants;
using Proyecto_Web.Data;
using Proyecto_Web.Models;
using Proyecto_Web.ViewModels;
using Proyecto_Web.ViewModels.Categories;

namespace Proyecto_Web.Controllers
{
    [Authorize(Roles = RoleNames.Administrator)]
    public class CategoriesController : Controller
    {
        private readonly NewsContext _newsContext;

        public CategoriesController(NewsContext newsContext)
        {
            this._newsContext = newsContext;
        }
        // GET: CategoryController
        public ActionResult Index(int page = 1, int pageSize = 5, string search = null)
        {
            var viewModel = new CategoryListViewModel { Search = search };
            var query = _newsContext.Categories.AsQueryable();

            var pageInfo = Pagination.GetInfo(page, pageSize);

            int total = 0;

            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(a => EF.Functions.Like(a.CategoryName, $"%{search}%"));

                total = query.Count();

                viewModel.Categories = query.Skip(pageInfo.Skip).Take(pageInfo.Take).ToList();

            }
            else
            {
                total = query.Count();
                viewModel.Categories = query.Skip(pageInfo.Skip).Take(pageInfo.Take).ToList();
            }

            viewModel.Pagination = new Pagination
            {
                Page = page,
                PageSize = pageSize,
                Total = total
            };

            return View(viewModel);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View(new CreateCategoryViewModel());
        }

        // POST: CategoriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCategoryViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var category = new Category();
                    category.CategoryName = viewModel.CategoryName;
                    category.Description = viewModel.Description;
                    _newsContext.Categories.Add(category);
                    _newsContext.SaveChanges();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    viewModel.Exception = ex;
                    return View(viewModel);
                }

            }

            return View(viewModel);
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {

            var Category = _newsContext.Categories.Find(id);
            var viewModel = new UpdateCategoryViewModel();
            viewModel.CategoryId = Category.CategoryId;
            viewModel.CategoryName = Category.CategoryName;
            viewModel.Description = Category.Description;

            return View(viewModel);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, UpdateCategoryViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var category = _newsContext.Categories.Find(id);
                    category.CategoryName = viewModel.CategoryName;
                    category.Description = viewModel.Description;
                    _newsContext.SaveChanges();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    viewModel.Exception = ex;
                    return View(viewModel);
                }
            }
            return View(viewModel);
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            var Category = _newsContext.Categories.Find(id);
            var viewModel = new DeleteCategoryViewModel();
            viewModel.CategoryId = Category.CategoryId;
            viewModel.CategoryName = Category.CategoryName;
            viewModel.Description = Category.Description;
            return View(viewModel);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection _)
        {
            var Category = _newsContext.Categories.Find(id);
            var viewModel = new DeleteCategoryViewModel();
            viewModel.CategoryId = Category.CategoryId;
            viewModel.CategoryName = Category.CategoryName;
            viewModel.Description = Category.Description;

            try
            {
                _newsContext.Categories.Remove(_newsContext.Categories.Find(id));
                _newsContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                viewModel.Exception = ex;
                return View(viewModel);
            }
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proyecto_Web.Data;
using Proyecto_Web.ViewModels.Categories;
using Proyecto_Web.ViewModels;
using Proyecto_Web.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Proyecto_Web.Constants;
using Proyecto_Web.Models;

namespace Proyecto_Web.Controllers
{
    [Authorize(Roles = RoleNames.Administrator)]

    public class UsersController : Controller
    {
        private readonly NewsContext _newsContext;

        public UsersController(NewsContext newsContext)
        {
            this._newsContext = newsContext;
        }

		public ActionResult Index(int page = 1, int pageSize = 5, string search = null)
		{
			var viewModel = new UsersListViewModel {Search = search };
			var query = _newsContext.Users.Include(u => u.Role).AsQueryable();														

			var pageInfo = Pagination.GetInfo(page, pageSize);

			int total = 0;

			if (!string.IsNullOrEmpty(search))
			{
				query = query.Where(a => EF.Functions.Like(a.FirstName, $"%{search}%"));

				total = query.Count();

				viewModel.User = query.Skip(pageInfo.Skip).Take(pageInfo.Take).ToList();

			}
			else
			{
				total = query.Count();
				viewModel.User = query.Skip(pageInfo.Skip).Take(pageInfo.Take).ToList();
			}

			viewModel.Pagination = new Pagination
			{
				Page = page,
				PageSize = pageSize,
				Total = total
			};

			return View(viewModel);
		}

		// GET: UsersController/Details/5
		public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Edit/5
        public ActionResult Edit(int id)
        {
			var user= _newsContext.Users.Find(id);
			var viewModel = new UpdateUsersViewModel();

			viewModel.UserId = user.UserId;
			viewModel.FirtName = user.FirstName;
			viewModel.LastName = user.LastName;
            viewModel.Email = user.Email;
            viewModel.Password = user.Password;
			user.RoleId = _newsContext.Roles.FirstOrDefault(r => r.RoleName == viewModel.Role)?.RoleD;

			return View(viewModel);
		}

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, UpdateUsersViewModel viewModel)
        {
			if (ModelState.IsValid)
			{
				try
				{
					var user = _newsContext.Users.Find(id);
					user.FirstName = viewModel.FirtName;
					user.LastName = viewModel.LastName;
                    user.Email = viewModel.Email;
                    user.Password = viewModel.Password;
					user.RoleId = _newsContext.Roles.FirstOrDefault(r => r.RoleName == viewModel.Role)?.RoleD;
					_newsContext.SaveChanges();

					return RedirectToAction(nameof(Index));
				}
				catch (Exception ex)
				{
					viewModel.Exception = ex;
					return View(viewModel);
				}
			}
			return View(viewModel);
		}

		// GET: UsersController/Delete/5
		public ActionResult Delete(int id)
		{
			var User = _newsContext.Users.Find(id);
			var viewModel = new DeleteUserViewModel();
            viewModel.UserId = User.UserId;
            viewModel.FirstName = User.FirstName;
            viewModel.LastName = User.LastName;
            viewModel.Email = User.Email;
            viewModel.Password = User.Password;
            User.RoleId = _newsContext.Roles.FirstOrDefault(r => r.RoleName == viewModel.Role)?.RoleD;


            return View(viewModel);
		}

		// POST: UsersController/Delete/5
		[HttpPost]
        [ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection _)
		{
			var User = _newsContext.Users.Find(id);
			var viewModel = new DeleteUserViewModel();
			viewModel.UserId = User.UserId;
			viewModel.FirstName = User.FirstName;
			viewModel.LastName = User.LastName;
			viewModel.Email = User.Email;
			viewModel.Password = User.Password;
            User.RoleId = _newsContext.Roles.FirstOrDefault(r => r.RoleName == viewModel.Role)?.RoleD;


            try
            {
				_newsContext.Users.Remove(_newsContext.Users.Find(id));
				_newsContext.SaveChanges();

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				viewModel.Exception = ex;
				return View(viewModel);
			}
		}
	}
}

Views/Shared/_Layout.cshtml
@using Proyecto_Web.Constants
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto_Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proyecto_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      
                        @if (User.IsInRole(RoleNames.Administrator))
                        {
					    	<li class="nav-item">
							    <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
						    </li>
						    <li class="nav-item">
						    	<a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
					    	</li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">News</a>
                            </li>
                        }
                        else if(User.IsInRole(RoleNames.Editor))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">News</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">Register</a>
                            </li>
                        }
                    </ul>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Proyecto_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Pagination.cshtml
@using Proyecto_Web.ViewModels
@model Pagination
<nav aria-label="Pagination">
	<ul class="pagination" style="background-color: #fff; padding: 10px; border-radius: 5px; display: flex; align-items: center;">
		<li class="page-item">
			<a class="page-link" href="@Url.Action(null, new {page = 1})" style="color: #fff; background-color: #000; padding: 6px 12px; display: flex; align-items: center;"><<</a>
		</li>
		@if (Model.HasPrevious)
		{
			<li class="page-item">
				<a class="page-link" href="@Url.Action(null, new {page = Model.Page - 1})" style="color: #fff; background-color: #000; padding: 6px 12px; display: flex; align-items: center;">Previous</a>
			</li>
		}
		else
		{
			<li class="page-item disabled" style="opacity: 0.5;">
				<a class="page-link" style="color: #fff; background-color: #000; padding: 6px 12px; display: flex; align-items: center;">Previous</a>
			</li>
		}

		<li class="page-item">
			<span style="padding: 6px 12px; font-weight: bold; background-color: #000; color: #fff; border-radius: 4px; display: flex; align-items: center;">Page @Model.Page of @Model.PageCount</span>
		</li>

		@if (Model.HasNext)
		{
			<li class="page-item">
				<a class="page-link" href="@Url.Action(null, new {page = Model.Page + 1})" style="color: #fff; background-color: #000; padding: 6px 12px; display: flex; align-items: center;">Next</a>
			</li>
		}
		else
		{
			<li class="page-item disabled" style="opacity: 0.5;">
				<a class="page-link" style="color: #fff; background-color: #000; padding: 6px 12px; display: flex; align-items: center;">Next</a>
			</li>
		}
		<li class="page-item">
			<a class="page-link" href="@Url.Action(null, new {page = Model.PageCount})" style="color: #fff; background-color: #000; padding: 6px 12px; display: flex; align-items: center;">>></a>
		</li>
	</ul>
	<div class="d-flex justify-content-between" style="color: #000; margin-left: 10px; font-weight: bold;">
		<span>Total items: @Model.Total</span>
	</div>

</nav>