ViewModels/Home/HomeIndexViewModel.cs
namespace Proyecto_Web.ViewModels.Home
{
    public class HomeIndexViewModel
    {
        public string Lang { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proyecto_Web.Constants;
using Proyecto_Web.Models;
using Proyecto_Web.ViewModels.Home;
using System.Diagnostics;

namespace Proyecto_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var lang = Request.Cookies[CookieNames.Lang];

            return View(new HomeIndexViewModel { Lang = lang});
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto_Web.Constants;

namespace Proyecto_Web.Controllers
{
    public class LanguageController : Controller
    {
        public IActionResult SetLanguage(string Lang)
        {
            Response.Cookies.Append(CookieNames.Lang, Lang);

            return Redirect("/");
        }
    }
}

Views/Home/Index.cshtml
@using Proyecto_Web.ViewModels.Home
@model HomeIndexViewModel;
@{
    ViewData["Title"] = "Home Page";
}

<div class=" d-flex">
    <a href="@Url.Action("SetLanguage", "Language", new {Lang = "es"})" class="me-5">
        ES
    </a>

    <a href="@Url.Action("SetLanguage", "Language", new { Lang = "en" })" class="me-5">
        EN
    </a>
</div>

@if (Model.Lang == "es")
{
    <div class="text-center">
        <h1 class="display-4">Bienvenido</h1>
        <p>Aprende sobre <a href="https://learn.microsoft.com/aspnet/core">Crear sitios web con ASP.NET Core</a>.</p>
    </div>
}
else if (Model.Lang == "en")
{
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>
}